// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function JsLog(arg1) {
  return window['go']['main']['App']['JsLog'](arg1);
}

export function ScreenRecord() {
  return window['go']['main']['App']['ScreenRecord']();
}
